jwt:
  secret: mysupercomplexsecret

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false

spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3306/choiceai?allowMultiQueries=true
    password: sniegavirs
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: dizvabole@gmail.com
    password: hpnj cjgl qvpx muxq
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true